// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: proto/hello/hello.proto

package hello

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *HelloReq) Reset() {
	*x = HelloReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hello_hello_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReq) ProtoMessage() {}

func (x *HelloReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_hello_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReq.ProtoReflect.Descriptor instead.
func (*HelloReq) Descriptor() ([]byte, []int) {
	return file_proto_hello_hello_proto_rawDescGZIP(), []int{0}
}

func (x *HelloReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type WorldRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *WorldRsp) Reset() {
	*x = WorldRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hello_hello_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorldRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldRsp) ProtoMessage() {}

func (x *WorldRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_hello_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldRsp.ProtoReflect.Descriptor instead.
func (*WorldRsp) Descriptor() ([]byte, []int) {
	return file_proto_hello_hello_proto_rawDescGZIP(), []int{1}
}

func (x *WorldRsp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_proto_hello_hello_proto protoreflect.FileDescriptor

var file_proto_hello_hello_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2f, 0x68, 0x65,
	0x6c, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x22, 0x24, 0x0a, 0x08, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x24, 0x0a,
	0x08, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x32, 0x3c, 0x0a, 0x03, 0x46, 0x6f, 0x6f, 0x12, 0x35, 0x0a, 0x03, 0x42, 0x61,
	0x72, 0x12, 0x16, 0x2e, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f,
	0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x73, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x52, 0x73,
	0x70, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_hello_hello_proto_rawDescOnce sync.Once
	file_proto_hello_hello_proto_rawDescData = file_proto_hello_hello_proto_rawDesc
)

func file_proto_hello_hello_proto_rawDescGZIP() []byte {
	file_proto_hello_hello_proto_rawDescOnce.Do(func() {
		file_proto_hello_hello_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_hello_hello_proto_rawDescData)
	})
	return file_proto_hello_hello_proto_rawDescData
}

var file_proto_hello_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_hello_hello_proto_goTypes = []interface{}{
	(*HelloReq)(nil), // 0: sample.hello.HelloReq
	(*WorldRsp)(nil), // 1: sample.hello.WorldRsp
}
var file_proto_hello_hello_proto_depIdxs = []int32{
	0, // 0: sample.hello.Foo.Bar:input_type -> sample.hello.HelloReq
	1, // 1: sample.hello.Foo.Bar:output_type -> sample.hello.WorldRsp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_hello_hello_proto_init() }
func file_proto_hello_hello_proto_init() {
	if File_proto_hello_hello_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_hello_hello_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hello_hello_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorldRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_hello_hello_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hello_hello_proto_goTypes,
		DependencyIndexes: file_proto_hello_hello_proto_depIdxs,
		MessageInfos:      file_proto_hello_hello_proto_msgTypes,
	}.Build()
	File_proto_hello_hello_proto = out.File
	file_proto_hello_hello_proto_rawDesc = nil
	file_proto_hello_hello_proto_goTypes = nil
	file_proto_hello_hello_proto_depIdxs = nil
}
