package main

import (
	"fmt"
	"github.com/quexer/utee"
	"io/ioutil"
	"net/http"
)

func main(){

	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go

	req, err := http.NewRequest("GET", "https://xxxx.cn/HelmReport/Fans/ReportSummary?begin=2019-03-01&end=2019-03-01&timeUnit=0", nil)
	if err != nil {
		// handle err
	}
	req.Header.Set("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:65.0) Gecko/20100101 Firefox/65.0")
	req.Header.Set("Accept", "*/*")
	req.Header.Set("Accept-Language", "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2")
	req.Header.Set("Referer", "https://helm.mercedes-benz.com.cn/HelmReport/")
	req.Header.Set("X-Requested-With", "XMLHttpRequest")
	req.Header.Set("Connection", "keep-alive")
	req.Header.Set("Cookie", "__RequestVerificationToken_L0hlbG1SZXBvcnQ1=lKLDuFFQilxtQposFOCYDdfKmUbZfpV_78l0DJAn48b_lRRm-3On5fI49CZoVY5FmapcJ1_F_Yg63wgdKaPnGqr9RRCEAPiuZaFsRo_Ldww1; Registration.Report.AppCookie=tpszqaQeB5N-3yxO2Ll5vtEcPGoGxBLgge9jcN2wiyBbHcFees-J-Oq4BPbHPYuf7n5YLFRh76YjLwFLkiSeGn-5WkXv_BYEByFG6qwV3-9PnysKYCY4mNvDX6AnWkfYZ4eRxOukrN3brDv6CHQVvM2LH6KJTsZHNr1s48nPjRp_zsyffkjS5caNbDLWJstK0bmjCdfw1SLuli26Qk-uPdrka32c2vzKoPtpr-CPq3DLcLUsBc_8WBhS5Yu50q3FChAc_9GLg4FBL1KLqOSzcdSQsxVpsUAz-dv2-_sKQgEyAvV05pgF_nf84OXuhwqs5KcMH1K2Q3VwkGMKzizgDd_-QbANmMEB1l-qGdm8cAl46JwxN7Wwo02hJWRV9Gv3")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		// handle err
	}
	bs,err:=ioutil.ReadAll(resp.Body)
	utee.Chk(err)
	fmt.Println(string(bs))
	defer resp.Body.Close()
}
